import { ALGORITHMS, CATEGORY_ORDER } from '@/lib/algorithms';
import { AlgorithmGrid } from '@/components/AlgorithmGrid';
import { HeroGrid } from '@/components/HeroGrid';

export const metadata = {
  title: 'Algorithms | Classical ML From Scratch',
  description: 'All 12 classical ML algorithms — implementation, theory, and visualisations.',
};

export default function AlgorithmsIndexPage() {
  return (
    <>
      <section className="relative py-12 md:py-16 overflow-hidden border-b border-gray-200 dark:border-gray-800">
        <HeroGrid />
        <div className="relative max-w-5xl mx-auto px-4 md:px-6">
          <div className="text-[10px] font-mono tracking-[0.3em] uppercase text-gray-400 mb-2">
            ARCHIVE / 12 IMPLEMENTATIONS
          </div>
          <h1 className="font-orbitron text-3xl md:text-5xl font-bold tracking-tight mb-4">
            ALGORITHMS
          </h1>
          <p className="text-gray-600 dark:text-gray-300 max-w-2xl">
            Each algorithm is built from raw NumPy first, then verified against scikit-learn.
            Click any card for the math derivation, the implementation, and every plot generated by the script.
          </p>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-4 md:px-6 py-12">
        {CATEGORY_ORDER.map((category) => {
          const subset = ALGORITHMS.filter((a) => a.category === category);
          if (subset.length === 0) return null;
          return (
            <div key={category} className="mb-12">
              <h2 className="font-orbitron text-lg md:text-xl font-bold tracking-wider mb-4 pb-2 border-b border-gray-200 dark:border-gray-800">
                {category.toUpperCase()}
                <span className="ml-3 text-xs text-gray-400 font-mono">
                  [{String(subset.length).padStart(2, '0')}]
                </span>
              </h2>
              <AlgorithmGrid algorithms={subset} />
            </div>
          );
        })}
      </section>
    </>
  );
}
